# Generated by Django 4.1 on 2022-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='SubTitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
