# Generated by Django 4.1 on 2022-08-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0005_homepage_facebbok_homepage_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FrontEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
            ],
        ),
    ]
