# Generated by Django 4.1 on 2022-08-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_backend_frontend'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.TextField()),
                ('Address', models.TextField()),
                ('Study', models.TextField()),
            ],
        ),
    ]
