# Generated by Django 4.1 on 2022-08-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
