# Generated by Django 4.1 on 2022-08-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0008_about_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.ImageField(upload_to='')),
                ('Frontend', models.ImageField(upload_to='')),
                ('FullWebsite', models.ImageField(upload_to='')),
            ],
        ),
    ]
