# Generated by Django 4.1 on 2022-08-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0010_alter_project_frontend_alter_project_fullwebsite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
