# Generated by Django 4.1 on 2022-08-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0013_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=250)),
                ('Photo', models.ImageField(upload_to='project_image')),
                ('Descriptions', models.TextField()),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectInfoRelatedName', to='portfolioApp.category')),
            ],
        ),
    ]
