# Generated by Django 4.1 on 2022-08-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0014_projectinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='Project',
            new_name='Category',
        ),
    ]
