# Generated by Django 4.1 on 2022-08-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0015_rename_project_projectinfo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='Category',
            new_name='category',
        ),
    ]
