# Generated by Django 4.1 on 2022-08-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0017_rename_category_projectinfo_categoryoke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='categoryOke',
            new_name='category',
        ),
    ]
