# Generated by Django 4.1 on 2022-08-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0018_rename_categoryoke_projectinfo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='CreatedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
