# Generated by Django 4.1 on 2022-08-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0020_projectinfo_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='VideoLink',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
