# Generated by Django 4.1 on 2022-08-22 10:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0021_alter_projectinfo_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='Descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
