# Generated by Django 4.1 on 2022-08-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0022_alter_projectinfo_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='4_reasearch_image')),
                ('Title', models.TextField()),
                ('Authors', models.TextField()),
                ('PublishedDate', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='2_about_image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='Photo',
            field=models.ImageField(upload_to='1_home_image'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='Photo',
            field=models.ImageField(upload_to='3_project_image'),
        ),
    ]
