# Generated by Django 4.1 on 2022-08-22 10:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0023_research_alter_about_photo_alter_homepage_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='Authors',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
