# Generated by Django 4.1 on 2022-08-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0024_alter_research_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='PaperLink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
