# Generated by Django 4.1 on 2022-08-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0027_alter_projectinfo_createddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='PublishedDate',
            field=models.DateTimeField(),
        ),
    ]
