# Generated by Django 4.1 on 2022-08-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0031_alter_contact_createddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='CreatedDate',
        ),
    ]
