# Generated by Django 4.1 on 2022-08-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0032_remove_contact_createddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='Photo',
        ),
    ]
