# Generated by Django 4.1.3 on 2023-03-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0035_auto_20221201_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcount',
            name='TotlaNumberOfAPI',
            field=models.IntegerField(null=True),
        ),
    ]
