# Generated by Django 4.1.3 on 2023-03-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0036_projectcount_totlanumberofapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcount',
            old_name='TotalNumberDynamicWebsite',
            new_name='ServiceCountry',
        ),
        migrations.RenameField(
            model_name='projectcount',
            old_name='TotalNumberOfProject',
            new_name='TotalCliens',
        ),
        migrations.RenameField(
            model_name='projectcount',
            old_name='TotalNumberOfStaticWebsite',
            new_name='TotalProjects',
        ),
        migrations.RemoveField(
            model_name='projectcount',
            name='TotlaNumberOfAPI',
        ),
    ]
